language: generic
services:
  - docker

before_install:
  - docker build -t jbdiop/webrtc-app-test -f Dockerfile.test .

script:
  - docker run jbdiop/webrtc-app-test npm run test:ci

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "webrtc-app"
  env: "Webrtcapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-070674816621"
  bucket_path: "webrtc-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY